import 'package:flutter/material.dart';

class LanguageConstants {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'settings': 'Settings',
      'account': 'Account',
      'profile_info': 'Profile Information',
      'change_password': 'Change Password',
      'preferences': 'Preferences',
      'notifications': 'Push Notifications',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'about': 'About',
      'app_version': 'App Version',
      'terms': 'Terms of Service',
      'privacy': 'Privacy Policy',
      'home': 'Home',
      'cart': 'Cart',
      'wishlist': 'Wishlist',
      'profile': 'Profile',
      'default': 'Default Address',
      'my_addresses': 'My Addresses',
      'add_new_address': 'Add New Address',
      'edit_address': 'Edit Address',
      'full_name': 'Full Name',
      'enter_full_name': 'Enter your full name',
      'phone_number': 'Phone Number',
      'enter_phone': 'Enter your phone number',
      'email': 'Email Address',
      'enter_email': 'Enter your email address',
      'street_address': 'Street Address',
      'enter_street': 'House number, Street name',
      'city_province': 'City/Province',
      'select_city': 'Select city/province',
      'district': 'District',
      'select_district': 'Select district',
      'ward': 'Ward',
      'select_ward': 'Select ward',
      'name_required': 'Please enter recipient name',
      'phone_required': 'Please enter phone number',
      'email_required': 'Please enter email address',
      'address_required': 'Please enter street address',
      'city_required': 'Please select city/province',
      'district_required': 'Please select district',
      'ward_required': 'Please select ward',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'set_default': 'Set as Default',
      'delete_address': 'Delete Address',
      'delete_confirmation': 'Are you sure you want to delete this address?',
      'address_deleted': 'Address deleted successfully',
      'address_updated': 'Address updated successfully',
      'address_added': 'New address added successfully',
      'no_addresses': 'No addresses saved',
      'edit_profile': 'Edit Profile',
      'my_orders': 'My Orders',
      'my_wishlist': 'My Wishlist',
      'logout': 'Logout',
      'welcome': 'Welcome',
      'my_account': 'My Account',
      'help': 'Help & Support',
      'save_changes': 'Save Changes',
      'profile_updated': 'Profile updated successfully',
      'all': 'All',
      'pending': 'Pending',
      'processing': 'Processing',
      'shipped': 'Shipped',
      'delivered': 'Delivered',
      'order_number': 'Order #',
      'product_name': 'Product Name',
      'no_orders': 'No orders found',
      'search': 'Search',
      'featured': 'Featured Products',
      'popular': 'Popular Items',
      'new_arrivals': 'New Arrivals',
      'see_all': 'See All',
      'price': 'Price',
      'add_to_cart': 'Add to Cart',
      'search_hint': 'Search products...',
      'product_title': 'Burgundy Slim Fit',
      'product_description':
          'Pure cotton casual shirt, has a spread collar, button placket...',
      'shop_now': 'Shop Now',
      'view_all': 'View All',
      'added_to_wishlist': 'Added to wishlist!',
      'removed_from_wishlist': 'Removed from wishlist!',
      'shop': 'Shop',
      't-shirts': 'T-Shirts',
      'shirts': 'Shirts',
      'pants': 'Pants',
      'shoes': 'Shoes',
    },
    'vi': {
      'settings': 'Cài đặt',
      'account': 'Tài khoản',
      'profile_info': 'Thông tin cá nhân',
      'change_password': 'Đổi mật khẩu',
      'preferences': 'Tùy chọn',
      'notifications': 'Thông báo đẩy',
      'dark_mode': 'Chế độ tối',
      'language': 'Ngôn ngữ',
      'about': 'Thông tin',
      'app_version': 'Phiên bản',
      'terms': 'Điều khoản dịch vụ',
      'privacy': 'Chính sách bảo mật',
      'home': 'Trang chủ',
      'cart': 'Giỏ hàng',
      'wishlist': 'Yêu thích',
      'profile': 'Tài khoản',
      'default': 'Mặc định',
      'my_addresses': 'Địa chỉ của tôi',
      'add_new_address': 'Thêm địa chỉ mới',
      'edit_address': 'Sửa địa chỉ',
      'full_name': 'Họ và tên',
      'enter_full_name': 'Nhập họ và tên',
      'phone_number': 'Số điện thoại',
      'enter_phone': 'Nhập số điện thoại',
      'email': 'Địa chỉ email',
      'enter_email': 'Nhập địa chỉ email',
      'street_address': 'Địa chỉ cụ thể',
      'enter_street': 'Số nhà, tên đường',
      'city_province': 'Tỉnh/Thành phố',
      'select_city': 'Chọn tỉnh/thành phố',
      'district': 'Quận/Huyện',
      'select_district': 'Chọn quận/huyện',
      'ward': 'Phường/Xã',
      'select_ward': 'Chọn phường/xã',
      'name_required': 'Vui lòng nhập họ tên',
      'phone_required': 'Vui lòng nhập số điện thoại',
      'email_required': 'Vui lòng nhập địa chỉ email',
      'address_required': 'Vui lòng nhập địa chỉ',
      'city_required': 'Vui lòng chọn tỉnh/thành phố',
      'district_required': 'Vui lòng chọn quận/huyện',
      'ward_required': 'Vui lòng chọn phường/xã',
      'save': 'Lưu',
      'cancel': 'Hủy',
      'delete': 'Xóa',
      'edit': 'Sửa',
      'set_default': 'Đặt làm mặc định',
      'delete_address': 'Xóa địa chỉ',
      'delete_confirmation': 'Bạn có chắc chắn muốn xóa địa chỉ này?',
      'address_deleted': 'Đã xóa địa chỉ thành công',
      'address_updated': 'Cập nhật địa chỉ thành công',
      'address_added': 'Thêm địa chỉ mới thành công',
      'no_addresses': 'Chưa có địa chỉ nào',
      'edit_profile': 'Chỉnh sửa thông tin',
      'my_orders': 'Đơn hàng của tôi',
      'my_wishlist': 'Danh sách yêu thích',
      'logout': 'Đăng xuất',
      'welcome': 'Xin chào',
      'my_account': 'Tài khoản của tôi',
      'help': 'Trợ giúp & Hỗ trợ',
      'save_changes': 'Lưu thay đổi',
      'profile_updated': 'Cập nhật thông tin thành công',
      'all': 'Tất cả',
      'pending': 'Chờ xác nhận',
      'processing': 'Đang xử lý',
      'shipped': 'Đang giao',
      'delivered': 'Đã giao',
      'order_number': 'Đơn hàng #',
      'product_name': 'Tên sản phẩm',
      'no_orders': 'Không có đơn hàng nào',
      'search': 'Tìm kiếm',
      'featured': 'Sản phẩm nổi bật',
      'popular': 'Phổ biến',
      'new_arrivals': 'Hàng mới về',
      'see_all': 'Xem tất cả',
      'price': 'Giá',
      'add_to_cart': 'Thêm vào giỏ',
      'search_hint': 'Tìm kiếm sản phẩm...',
      'product_title': 'Áo Sơ Mi Slim Fit Màu Burgundy',
      'product_description':
          'Áo sơ mi cotton casual, cổ bẻ, khuy cài phía trước...',
      'shop_now': 'Mua Ngay',
      'view_all': 'Xem Tất Cả',
      'added_to_wishlist': 'Đã thêm vào mục yêu thích!',
      'removed_from_wishlist': 'Đã xóa khỏi mục yêu thích!',
      'shop': 'Cửa hàng',
      't-shirts': 'Áo thun',
      'shirts': 'Áo sơ mi',
      'pants': 'Quần',
      'shoes': 'Giày',
    }
  };
}

class LanguageProvider extends ChangeNotifier {
  String _currentLanguage = 'vi';

  String get currentLanguage => _currentLanguage;

  void setLanguage(String languageCode) {
    if (_currentLanguage != languageCode) {
      _currentLanguage = languageCode;
      notifyListeners();
    }
  }

  String translate(String key) {
    return LanguageConstants.translations[_currentLanguage]?[key] ?? key;
  }
}
