class ProductList {
  static final List<Map<String, dynamic>> products = [
    {
      'name': 'Sport T-Shirt',
      'name_vi': 'Áo thun nữ thể thao',
      'image': 'assets/images/ao1.jpg',
      'price': '31.99',
      'oldPrice': '45.99',
      'isFavorite': false,
      'category': 'T-Shirts',
      'booking': 'assets/images/ao5.jpg',
      'rating': 5,
      'isNew': true,
      'discount': 30,
    },
    {
      'name': 'Canvas T-Shirt',
      'name_vi': 'Áo thun vải Canvas',
      'image': 'assets/images/ao2.jpg',
      'price': '29.99',
      'oldPrice': '39.99',
      'isFavorite': false,
      'category': 'T-Shirts',
      'booking': 'assets/images/ao3.jpg',
      'rating': 4,
      'isNew': true,
    },
    {
      'name': 'Silk T-Shirt',
      'name_vi': 'Áo thun vải lụa',
      'image': 'assets/images/ao3.jpg',
      'price': '24.99',
      'oldPrice': '34.99',
      'isFavorite': false,
      'category': 'T-Shirts',
      'booking': 'assets/images/ao1.jpg',
      'rating': 5,
      'discount': 25,
    },
    {
      'name': 'Helmet T-Shirt',
      'name_vi': 'Áo thun Helmet',
      'image': 'assets/images/ao4.jpg',
      'price': '25.99',
      'oldPrice': '37.99',
      'isFavorite': false,
      'category': 'T-Shirts',
      'booking': 'assets/images/ao2.jpg',
      'rating': 4,
      'isNew': true,
    },

    // Pants
    {
      'name': 'Ripped Jeans',
      'name_vi': 'Quần Jeans rách lai',
      'image': 'assets/pants/pant1.jpg',
      'price': '35.99',
      'oldPrice': '39.99',
      'isFavorite': false,
      'category': 'Pants',
      'booking': 'assets/pants/pant1.jpg',
      'rating': 5,
      'isNew': true,
      'discount': 20,
    },
    {
      'name': 'Folded Jeans',
      'name_vi': 'Quần jeans bẻ lai',
      'image': 'assets/pants/pant2.jpg',
      'price': '39.99',
      'oldPrice': '45.99',
      'isFavorite': false,
      'category': 'Pants',
      'booking': 'assets/pants/pant2.jpg',
      'rating': 4,
      'discount': 15,
    },
    {
      'name': 'Classic Jeans',
      'name_vi': 'Quần jeans cổ điển',
      'image': 'assets/pants/pant3.jpg',
      'price': '37.99',
      'oldPrice': '42.99',
      'isFavorite': false,
      'category': 'Pants',
      'booking': 'assets/pants/pant3.jpg',
      'rating': 5,
      'isNew': true,
    },
    {
      'name': 'Cotton Shorts',
      'name_vi': 'Quần short giả chần bông',
      'image': 'assets/pants/pant4.jpg',
      'price': '37.99',
      'oldPrice': '42.99',
      'isFavorite': false,
      'category': 'Pants',
      'booking': 'assets/pants/pant4.jpg',
      'rating': 4,
      'discount': 20,
    },
  ];
}
